# Generated by Django 2.2.3 on 2019-11-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_rooms', models.CharField(max_length=10)),
                ('image', models.FileField(blank=True, upload_to='images')),
            ],
        ),
    ]
