# Generated by Django 2.2.3 on 2019-11-19 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='type_of_house',
        ),
    ]
